# **POLARS**

**1) Считывание датасета**

In [1]:
import polars as pl

df = pl.read_csv('train.csv')

**2. Выведение основной информации о датасете**

In [14]:
print('Статистическое описание датасета train.csv\nСредние значения указаны в строке "mean"')

df.describe()

Статистическое описание датасета train.csv
Средние значения указаны в строке "mean"

shape: (9, 13)
┌────────────┬─────────────┬──────────┬──────────┬───┬───────────┬───────────┬───────┬──────────┐
│ statistic  ┆ PassengerId ┆ Survived ┆ Pclass   ┆ … ┆ Ticket    ┆ Fare      ┆ Cabin ┆ Embarked │
│ ---        ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---   ┆ ---      │
│ str        ┆ f64         ┆ f64      ┆ f64      ┆   ┆ str       ┆ f64       ┆ str   ┆ str      │
╞════════════╪═════════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════╪══════════╡
│ count      ┆ 891.0       ┆ 891.0    ┆ 891.0    ┆ … ┆ 891       ┆ 891.0     ┆ 204   ┆ 889      │
│ null_count ┆ 0.0         ┆ 0.0      ┆ 0.0      ┆ … ┆ 0         ┆ 0.0       ┆ 687   ┆ 2        │
│ mean       ┆ 446.0       ┆ 0.383838 ┆ 2.308642 ┆ … ┆ null      ┆ 32.204208 ┆ null  ┆ null     │
│ std        ┆ 257.353842  ┆ 0.486592 ┆ 0.836071 ┆ … ┆ null      ┆ 49.693429 ┆ null  ┆ null     │
│ min        ┆ 1.0         ┆ 0.0      ┆ 1.0      ┆ … ┆ 110152    ┆ 0.0       ┆ A10   ┆ C        │
│ 25%        ┆ 224.0       ┆ 0.0      ┆ 2.0      ┆ … ┆ null      ┆ 7.925     ┆ null  ┆ null     │
│ 50%        ┆ 446.0       ┆ 0.0      ┆ 3.0      ┆ … ┆ null      ┆ 14.4542   ┆ null  ┆ null     │
│ 75%        ┆ 669.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ null      ┆ 31.0      ┆ null  ┆ null     │
│ max        ┆ 891.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ WE/P 5735 ┆ 512.3292  ┆ T     ┆ S        │
└────────────┴─────────────┴──────────┴──────────┴───┴───────────┴───────────┴───────┴──────────┘

In [11]:
result_str = str("Типы данных в датасете train.csv\n")
for i, (col_name, dtype) in enumerate(zip(df.columns, df.dtypes)):
    result_str += f"Колонка №{i} {col_name} - Тип данных {dtype}\n"
print(result_str)

Типы данных в датасете train.csv
Колонка №0 PassengerId - Тип данных Int64
Колонка №1 Survived - Тип данных Int64
Колонка №2 Pclass - Тип данных Int64
Колонка №3 Name - Тип данных String
Колонка №4 Sex - Тип данных String
Колонка №5 Age - Тип данных Float64
Колонка №6 SibSp - Тип данных Int64
Колонка №7 Parch - Тип данных Int64
Колонка №8 Ticket - Тип данных String
Колонка №9 Fare - Тип данных Float64
Колонка №10 Cabin - Тип данных String
Колонка №11 Embarked - Тип данных String

In [ ]:
print(df.null_count()) #Вывели нули в датасете. Имеем три колонки: Age, Cabin, Embarked, - с пропусками

shape: (1, 12)
┌─────────────┬──────────┬────────┬──────┬───┬────────┬──────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name ┆ … ┆ Ticket ┆ Fare ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---  ┆   ┆ ---    ┆ ---  ┆ ---   ┆ ---      │
│ u32         ┆ u32      ┆ u32    ┆ u32  ┆   ┆ u32    ┆ u32  ┆ u32   ┆ u32      │
╞═════════════╪══════════╪════════╪══════╪═══╪════════╪══════╪═══════╪══════════╡
│ 0           ┆ 0        ┆ 0      ┆ 0    ┆ … ┆ 0      ┆ 0    ┆ 687   ┆ 2        │
└─────────────┴──────────┴────────┴──────┴───┴────────┴──────┴───────┴──────────┘

In [ ]:
print(df.mean()) #Отдельный вывод средних значений каждой колонки

shape: (1, 12)
┌─────────────┬──────────┬──────────┬──────┬───┬────────┬───────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass   ┆ Name ┆ … ┆ Ticket ┆ Fare      ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---      ┆ ---  ┆   ┆ ---    ┆ ---       ┆ ---   ┆ ---      │
│ f64         ┆ f64      ┆ f64      ┆ str  ┆   ┆ str    ┆ f64       ┆ str   ┆ str      │
╞═════════════╪══════════╪══════════╪══════╪═══╪════════╪═══════════╪═══════╪══════════╡
│ 446.0       ┆ 0.383838 ┆ 2.308642 ┆ null ┆ … ┆ null   ┆ 32.204208 ┆ null  ┆ null     │
└─────────────┴──────────┴──────────┴──────┴───┴────────┴───────────┴───────┴──────────┘

**3. Подсчет количества пассажиров каждого класса**

In [16]:
print(df.get_column("Pclass").value_counts().sort("Pclass"))

shape: (3, 2)
┌────────┬───────┐
│ Pclass ┆ count │
│ ---    ┆ ---   │
│ i64    ┆ u32   │
╞════════╪═══════╡
│ 1      ┆ 216   │
│ 2      ┆ 184   │
│ 3      ┆ 491   │
└────────┴───────┘

**4. Вывод количества выживших мужчин и женщин на корабле**

In [23]:
print("Количество выживших по полу")
print(df.group_by(['Sex']).agg(pl.col('Survived').sum()))

Количество выживших по полу
shape: (2, 2)
┌────────┬──────────┐
│ Sex    ┆ Survived │
│ ---    ┆ ---      │
│ str    ┆ i64      │
╞════════╪══════════╡
│ female ┆ 233      │
│ male   ┆ 109      │
└────────┴──────────┘

**5. Вывод части таблицы, где возраст пассажиров больше 44 лет**

In [24]:
print(df.filter(pl.col('Age') > 44))

shape: (115, 12)
┌─────────────┬──────────┬────────┬──────────────────┬───┬────────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name             ┆ … ┆ Ticket     ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---              ┆   ┆ ---        ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str              ┆   ┆ str        ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪══════════════════╪═══╪════════════╪═════════╪═══════╪══════════╡
│ 7           ┆ 0        ┆ 1      ┆ McCarthy, Mr.    ┆ … ┆ 17463      ┆ 51.8625 ┆ E46   ┆ S        │
│             ┆          ┆        ┆ Timothy J        ┆   ┆            ┆         ┆       ┆          │
│ 12          ┆ 1        ┆ 1      ┆ Bonnell, Miss.   ┆ … ┆ 113783     ┆ 26.55   ┆ C103  ┆ S        │
│             ┆          ┆        ┆ Elizabeth        ┆   ┆            ┆         ┆       ┆          │
│ 16          ┆ 1        ┆ 2      ┆ Hewlett, Mrs.    ┆ … ┆ 248706     ┆ 16.0    ┆ null  ┆ S        │
│             ┆          ┆        ┆ (Mary D          ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ Kingcome…        ┆   ┆            ┆         ┆       ┆          │
│ 34          ┆ 0        ┆ 2      ┆ Wheadon, Mr.     ┆ … ┆ C.A. 24579 ┆ 10.5    ┆ null  ┆ S        │
│             ┆          ┆        ┆ Edward H         ┆   ┆            ┆         ┆       ┆          │
│ 53          ┆ 1        ┆ 1      ┆ Harper, Mrs.     ┆ … ┆ PC 17572   ┆ 76.7292 ┆ D33   ┆ C        │
│             ┆          ┆        ┆ Henry Sleeper    ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ (My…             ┆   ┆            ┆         ┆       ┆          │
│ …           ┆ …        ┆ …      ┆ …                ┆ … ┆ …          ┆ …       ┆ …     ┆ …        │
│ 858         ┆ 1        ┆ 1      ┆ Daly, Mr. Peter  ┆ … ┆ 113055     ┆ 26.55   ┆ E17   ┆ S        │
│             ┆          ┆        ┆ Denis            ┆   ┆            ┆         ┆       ┆          │
│ 863         ┆ 1        ┆ 1      ┆ Swift, Mrs.      ┆ … ┆ 17466      ┆ 25.9292 ┆ D17   ┆ S        │
│             ┆          ┆        ┆ Frederick Joel   ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ (Ma…             ┆   ┆            ┆         ┆       ┆          │
│ 872         ┆ 1        ┆ 1      ┆ Beckwith, Mrs.   ┆ … ┆ 11751      ┆ 52.5542 ┆ D35   ┆ S        │
│             ┆          ┆        ┆ Richard Leonard… ┆   ┆            ┆         ┆       ┆          │
│ 874         ┆ 0        ┆ 3      ┆ Vander Cruyssen, ┆ … ┆ 345765     ┆ 9.0     ┆ null  ┆ S        │
│             ┆          ┆        ┆ Mr. Victor       ┆   ┆            ┆         ┆       ┆          │
│ 880         ┆ 1        ┆ 1      ┆ Potter, Mrs.     ┆ … ┆ 11767      ┆ 83.1583 ┆ C50   ┆ C        │
│             ┆          ┆        ┆ Thomas Jr (Lily  ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ A…               ┆   ┆            ┆         ┆       ┆          │
└─────────────┴──────────┴────────┴──────────────────┴───┴────────────┴─────────┴───────┴──────────┘

# **УСКОРЕНИЕ РАБОТЫ С PANDAS**

**1. Считывание датасета**

In [25]:
import pandas as pd
import bottleneck as bn

df_pd = pd.read_csv('train.csv')

**2. Подсчет среднего возраста пассажиров и его стандартного отклонения с помощью bottleneck**

In [28]:
print(f"Средний возраст пассажиров: {bn.nanmean(df_pd['Age']):.0f}")
print(f"Стандартное отклонение возраста пассажиров: {bn.nanstd(df_pd['Age']):.2f}")

Средний возраст пассажиров: 30
Стандартное отклонение возраста пассажиров: 14.52

**3. Получение столбца Fare_new как Fare * 1.3**

In [31]:
df_pd['Fare_new'] = df_pd['Fare'].apply(lambda x: x * 1.3)
print(df_pd[['Fare', 'Fare_new']])

        Fare  Fare_new
0     7.2500   9.42500
1    71.2833  92.66829
2     7.9250  10.30250
3    53.1000  69.03000
4     8.0500  10.46500
..       ...       ...
886  13.0000  16.90000
887  30.0000  39.00000
888  23.4500  30.48500
889  30.0000  39.00000
890   7.7500  10.07500

[891 rows x 2 columns]

# **ОПТИМИЗАЦИЯ ТИПОВ PANDAS**

**1. Считывание датасета Housing.csv**

In [33]:
df_house = pd.read_csv("Housing.csv")

**2. Определение оптимального типа данных для колонок датасета**

In [ ]:
df_house.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 221.9 KB

Мы видим 2 основных типа данных: int64 и object. Для числовых значений мы можем уменьшить **разрядность**. Кроме того можно учесть, являются ли числа неотрицательными. Для object мы можем воспользоваться **категориальным** типом данных

In [40]:
print("\nДиапазоны числовых столбцов:")
numeric_data = ['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'parking']
for col in numeric_data:
    print(f"{col}: min = {df_house[col].min()}, max = {df_house[col].max()}")

Диапазоны числовых столбцов:
price: min = 1750000, max = 13300000
area: min = 1650, max = 16200
bedrooms: min = 1, max = 6
bathrooms: min = 1, max = 4
stories: min = 1, max = 4
parking: min = 0, max = 3

Соответственно для **price** - **uint32** (от 0 до 4.294.967.295), **area** - **uint16** (от 0 до 65535), для **bedrooms**, **bathrooms**, **stories**, **parking** - **uint8** (от 0 до 255)

**3. Смена типа данных столбцов датасета**

In [43]:
categorical_data = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea', 'furnishingstatus']
opt_numeric = ["uint32", "uint16", "uint8", "uint8", "uint8", "uint8"]
for col, type in zip(numeric_data, opt_numeric):
    df_house[col] = df_house[col].astype(type)
for col in categorical_data:
    df_house[col] = df_house[col].astype('category')

In [44]:
df_house.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    uint32
 1   area              545 non-null    uint16
 2   bedrooms          545 non-null    uint8
 3   bathrooms         545 non-null    uint8
 4   stories           545 non-null    uint8
 5   mainroad          545 non-null    category
 6   guestroom         545 non-null    category
 7   basement          545 non-null    category
 8   hotwaterheating   545 non-null    category
 9   airconditioning   545 non-null    category
 10  parking           545 non-null    uint8
 11  prefarea          545 non-null    category
 12  furnishingstatus  545 non-null    category
dtypes: category(7), uint16(1), uint32(1), uint8(4)
memory usage: 10.7 KB

**БЫЛО** - 221.9КБ

**СТАЛО** - 10.7КБ

**ВЫВОД** - Сократили размер массива на 95%